Landing page
danopolan/istqb_latex pull request #36
Opened 2023-07-17 21:11 UTC by Witiko

Closes #17.

Here is the landing page of `example.tex` generated from metadata in `example.yml`:

``` yml
schema: Certified Tester
level: Foundation Level
code: example
version: Version 2018 V3.1
date: 11 November 2019
release: For public release
```

![ISTQB_Example_Document](https://github.com/danopolan/istqb_latex/assets/603082/b7f947ee-33c9-4b81-9beb-b15df88fa388)

2023-07-18 08:53 UTC, danopolan requested changes

2023-07-18 08:53 UTC, danopolan commented on istqb.cls
> +    \g_istqb_level_str{}~Syllabus
Few things on a syllabus name:
1. We should add `schema` as "Certified Tester" as the first line of syllabus name
2. Second line will be `level` so "Advanced Level" sot ATLaS
3. Third line will be a syllabus `title` so "Agile Test Leadership at Scale"
4. Fourth line will be test "Syllabus"

Hopefully it will fit :)

2023-07-18 13:19 UTC, Witiko commented on istqb.cls
> +    \g_istqb_level_str{}~Syllabus
Can I see an example of what the expected formatting would be (font size, vertical spacing, etc.)? I followed the Word template, which containes none of the requested lines. The CTFL 4.0 syllabus contains the schema line that you mention in point 1, but I was told not to follow the CTFL 4.0 syllabus in #17, so the formatting may be incorrect.

2023-07-19 06:43 UTC, danopolan commented on istqb.cls
> +    \g_istqb_level_str{}~Syllabus
Yes, unfortunatelly, template is not giving us the best example here, nor CTFL 4.0 syllabus, which has super short name compared to other syllabi.
One of the examples could be [CTAL TTA](https://istqb-main-web-prod.s3.amazonaws.com/media/documents/ISTQB-CTAL-TTA_Syllabus_v4.0.pdf) or CTAL ATT (https://istqb-main-web-prod.s3.amazonaws.com/media/documents/ISTQB-CTAL-ATT_Syllabus_v1.1.pdf).
But you see they are not consistent, and that is also why we are creating this LaTeX template. So the newly set standard should be as mentioned in the PR comment.

2023-07-19 11:07 UTC, Witiko commented on istqb.cls
> +    \g_istqb_level_str{}~Syllabus
Here are the updated landing pages for example.tex (on the left) and atlas.tex (on the right):

![example-landing-pages](https://github.com/danopolan/istqb_latex/assets/603082/35195e34-a3fc-44c5-82ca-ecb774cae514)

2023-07-19 11:58 UTC, danopolan approved these changes

2023-07-19 13:41 UTC, merged