Improve example document
danopolan/istqb_latex pull request #76
Opened 2023-08-21 19:20 UTC by Witiko

Will close #64 when it is completed. Currently a work in progress published as a draft here, so that we can discuss the direction.

### Tasks

- Improve the documentation of the following sections, so that example code is shown for all markdown outputs and so that all formatting options are shown to the user. The sections are listed in the order of appearance in the example document:
  - [ ] Learning objectives
  - [ ] Lists
  - [ ] Section references
  - [ ] Figures
  - [x] Tables
  - [x] References
  - [ ] Indexing

2023-08-27 12:25 UTC, danopolan requested changes

2023-08-27 21:14 UTC, Witiko commented on example-istqb-content.md
>  ## Section name {#section-name}
By placeholder text, you mean 0-switch coverage, functional appropriateness, and component integration testing? The purpose of adding three example terms was to have the *Index* section contain more than one term, so that users could see how the *Index* section would be formatted, similarly to the example of bibliographic references.

However, I can add just a single example: `[term]{.index}`. Is this what you have in mind?

2023-08-28 15:05 UTC, danopolan commented on example-istqb-content.md
>  ## Section name {#section-name}
Sorry I had to place comment on the last line of diff, but I meant to remove everything from Line 220
https://github.com/danopolan/istqb_latex/blob/298734df7ca9f70ea5841c5f3d50cc6374e88947/example-istqb-content.md?plain=1#L220

2023-08-30 11:45 UTC, Witiko commented
@danopolan Should be ready for a review and merge.

2023-09-07 12:10 UTC, Witiko commented
@danopolan https://github.com/danopolan/istqb_latex/issues/68 will need adding support for landscape content, which will also need documentation. Since this PR has not yet been approved, I will add both the support and the documentation for landscape content here.

2023-09-18 08:53 UTC, Witiko commented
In order to document labeling tables without hybrid Markdown+LaTeX markup, I merged #77 to this PR.

2023-09-18 09:21 UTC, merged