Example updated with ISTQB guidelines
danopolan/istqb_latex pull request #89
Opened 2023-10-27 17:53 UTC by danopolan

- [ ] Add ISTQB writing guidelines into `example.pdf`
- [ ] Other updates of MD guidelines in `example.pdf`
- [ ] Added guidelines on landing page
- [ ] `./example-md/metadata.yml` updated
- [ ] Update structure of MD files in `./example-md/`
- [ ] Product Level moved before Product Name on landing page

2023-10-27 18:30 UTC, Witiko requested changes

2023-10-27 18:30 UTC, Witiko commented on example-md/00-introduction.md
> +*	K6: Create
Unexpected tab.

2023-10-27 18:30 UTC, Witiko commented on example-md/00-introduction.md
> +*	H0: This can include a live demo of an exercise or recorded video. Since this is not performed by the trainee, it is not strictly an exercise.
Unexpected tab.

2023-10-27 18:30 UTC, Witiko commented on example-md/01-writing-guidelines.md
> +    Normal size+/-20% shall be accepted; authors shall justify deviations to the Product Owner.
```suggestion
    Normal size +/-20% shall be accepted; authors shall justify deviations to the Product Owner.
```

2023-10-27 18:30 UTC, Witiko commented on example-md/00-introduction.md
> +*	K6: Create
```suggestion
* K6: Create
```

2023-10-27 18:30 UTC, Witiko commented on example-md/00-introduction.md
> +*	H0: This can include a live demo of an exercise or recorded video. Since this is not performed by the trainee, it is not strictly an exercise.
```suggestion
* H0: This can include a live demo of an exercise or recorded video. Since this is not performed by the trainee, it is not strictly an exercise.
```

2023-10-27 18:30 UTC, Witiko commented on example-md/02-markdown-guidelines.md
> +```yaml
````suggestion

```yaml
````

2023-10-27 18:30 UTC, Witiko commented on example-md/02-markdown-guidelines.md
> +```
````suggestion
```

````

2023-10-27 18:30 UTC, Witiko commented on example-md/02-markdown-guidelines.md
> +To exclude section from Table of Content , write `{-}` next to the section heading as follows:
Writing `{-}` is short for `{.unnumbered}`. The section is included in the Table of Contents, it's just unnumbered.

```suggestion
To make a section unnumbered, write `{-}` next to the section heading as follows:
```

2023-10-27 18:30 UTC, Witiko commented on example-md/metadata.yml
> +date: 31 Octobver 2023
```suggestion
date: 31 October 2023
```

2023-10-27 18:30 UTC, Witiko commented on example.tex
> +\markdownInput{example-md/03-architecture.md}
Changes to the structure of `example.tex` should be documented in `example-md/03-architecture.md`.

2023-10-27 18:30 UTC, Witiko commented on example-md/revisions.md
> -ASQF V2.2 | 07.2003 | ASQF Syllabus Foundation Level Version v2.2 ``Lehrplan Grundlagen %
The removal of this line, which used `%` to split the table row to two lines means that we no longer need the `texComments` syntax extension here. Therefore, `\markdownInput[texComments]{example-md/revisions.md}` in `example.md` can be replaced with `\markdownInput{example-md/revisions.md}`.

In `example-md/03-architecture.md`, we discuss on the `texComments` option:

``` md
     Here, the `texComments` option is used to allow the breaking of long lines in the revision table using the percent sign (`%`).
     You may use more `\markdownInput` `\LaTeX`{=tex} commands to include additional markdown documents. For each `\markdownInput`
     command, you may provide options supported by the Markdown package for `\TeX`{=tex} [@novotny:2023] like `texComments` to alter the flavor
     of markdown used in the markdown document.
```

After the `texComments` option has been removed from `example.tex`, this discussion can be simplified as follows:

``` md
You may use more `\markdownInput` `\LaTeX`{=tex} commands to include additional markdown documents.
```

2023-10-27 18:35 UTC, Witiko commented on example-md/02-markdown-guidelines.md
> +## Sections {-}
```suggestion
## Unnumbered section {-}
```

2023-10-30 15:59 UTC, danopolan reviewed
Review comments implemented.

2023-10-30 15:59 UTC, danopolan commented on example.tex
> +\markdownInput{example-md/03-architecture.md}
Done. Thx for spotting this.

2023-10-30 15:59 UTC, danopolan commented on example-md/revisions.md
> -ASQF V2.2 | 07.2003 | ASQF Syllabus Foundation Level Version v2.2 ``Lehrplan Grundlagen %
I have put the long line back so the documentation covers as many cases as possible.

2023-10-30 16:27 UTC, danopolan commented on example-md/revisions.md
> -ASQF V2.2 | 07.2003 | ASQF Syllabus Foundation Level Version v2.2 ``Lehrplan Grundlagen %
@Witiko I did put the % sign back, but it looks like, line breaks are not required in the tables. And if used, it doesn't do anything. What's wrong here?

```markdown
| Version | Date | Remarks |
|---------|------|---------|
vM.mm | YYYY/MM/DD |  Maintenance release with minor updates on chapters 2, 4, 5
v4.0 | YYYY/MM/DD | General release version
v3.1.1 | YYYY/MM/DD | Copyright and logo update
v1.2.3 | YYYY/MM/DD | If remaks are longer, they can be split into more lines by using the percent sign % 
which serves as a line break.
```

<img width="533" alt="image" src="https://github.com/danopolan/istqb_latex/assets/95688217/52dd8e6b-0b78-423e-91df-8cddc0e26b6a">

2023-10-30 17:53 UTC, Witiko commented on example-md/revisions.md
> -ASQF V2.2 | 07.2003 | ASQF Syllabus Foundation Level Version v2.2 ``Lehrplan Grundlagen %
The percent sign (`%`) gives you the ability to break long lines in the input text even at places where this is usually not allowed such as table rows, hyperlinks, and section headings. You may also write short comments after the percent sign. Both the percent sign and any comments following it produce no visible output in the PDF document.

You may want to use the above explanation in the example document.

2023-10-30 18:18 UTC, Witiko approved these changes

2023-10-30 18:37 UTC, merged